[slack]
webhook_url = "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"

[database]
driver = "postgresql"
host = "postgres"
port = 5432
database = "wallets"
username = "user"
password = "password"

[blockchains]
kujira = "https://kujira-rpc.nodes.defiantlabs.net"
