version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  app:
    build: .
    restart: "unless-stopped"
    networks:
      default:
        aliases:
          - app
    <<: *logging
